### ISSUE TITLE
Why is this not popular?

### ISSUE THREAD

**Issue by mightyiam** [MaxArt2501/re-build#4]
Is there a better alternative?

**Comment by MaxArt2501** [comment]
I don't know the reasons - and I don't care much about them, to be honest. I made this library as an expertiment :)

As I mentioned in the readme, there's VerbalExpressions as an alternative. I wouldn't say it's *better*, as you can't do everything ECMAScript's regular expressions can do, but this is due to the fact that VerbalExpressions as available for many languages, not only JavaScript. Being this limited in its functionality, it also has a slightly more expressive API.

Anyway, a major overhaul of RE-Build's code is underway, as it is quite messy right now.

Closing this issue, but feel free to comment further.
